# Generated by Django 4.2.5 on 2023-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.URLField(blank=True, null=True)),
                ('open_time', models.DateField()),
                ('gym_logo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
